# Generated by Django 6.0.8 on 2026-09-11 04:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_driverlocation_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('ACCEPTED', 'ACCEPTED'), ('DRIVER_ARRIVING', 'DRIVER_ARRIVING'), ('STARTED', 'STARTED'), ('COMPLETED', 'COMPLETED')], default='REQUESTED', max_length=20)),
                ('pickup_location', models.CharField(default='Vizag', max_length=255)),
                ('drop_location', models.CharField(default='RK Beach', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DriverLocation',
        ),
    ]
