# Generated by Django 6.0.8 on 2026-08-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
