# Generated by Django 6.0.8 on 2026-09-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ride_created_at_ride_drop_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='passenger_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_type',
            field=models.CharField(choices=[('standard', 'standard'), ('premium', 'premium'), ('shared', 'shared')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='ride',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
