# Generated by Django 6.0.8 on 2026-09-11 06:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ride_delete_driverlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='drop_location',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='pickup_location',
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_heading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='drop_lat',
            field=models.FloatField(default=17.73),
        ),
        migrations.AddField(
            model_name='ride',
            name='drop_lng',
            field=models.FloatField(default=83.32),
        ),
        migrations.AddField(
            model_name='ride',
            name='passenger_id',
            field=models.CharField(default='passenger_123', max_length=100),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_lat',
            field=models.FloatField(default=17.7231),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_lng',
            field=models.FloatField(default=83.3012),
        ),
        migrations.AlterField(
            model_name='ride',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('ACCEPTED', 'ACCEPTED'), ('DRIVER_ARRIVING', 'DRIVER_ARRIVING'), ('STARTED', 'STARTED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='REQUESTED', max_length=20),
        ),
    ]
