# Generated by Django 6.0.8 on 2026-09-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ride_passenger_info_ride_ride_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='fare',
            field=models.IntegerField(default=0),
        ),
    ]
