# Generated by Django 6.0.8 on 2026-09-02 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ride_fare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='distance_km',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='ride',
            name='duration_min',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='ride',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides_as_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='customer_name',
            field=models.CharField(default='Test User', max_length=100),
        ),
    ]
