# Generated by Django 6.0.8 on 2026-09-04 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ride_distance_km_ride_duration_min_ride_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='drop_location',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='passenger_info',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='ride_type',
        ),
        migrations.AddField(
            model_name='ride',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='duration_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='fare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('ACCEPTED', 'ACCEPTED'), ('STARTED', 'STARTED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='REQUESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='ride',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='DriverProfile',
        ),
    ]
