# Generated by Django 6.0.8 on 2026-09-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_driverprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='duration_min',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='user',
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='drop_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
