# Generated by Django 6.0.8 on 2026-09-07 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ride_customer_ride_fare_ride_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='ride',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status'], name='core_ride_status_7586b8_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['created_at'], name='core_ride_created_061161_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver_name'], name='core_ride_driver__2eed07_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['customer'], name='core_ride_custome_169c66_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status', 'created_at'], name='core_ride_status_11d531_idx'),
        ),
    ]
