# Generated by Django 6.0.8 on 2026-09-08 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_ride_options_alter_ride_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ride',
            name='core_ride_status_7586b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='ride',
            name='core_ride_created_061161_idx',
        ),
        migrations.RemoveIndex(
            model_name='ride',
            name='core_ride_driver__2eed07_idx',
        ),
        migrations.RemoveIndex(
            model_name='ride',
            name='core_ride_custome_169c66_idx',
        ),
        migrations.RemoveIndex(
            model_name='ride',
            name='core_ride_status_11d531_idx',
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['customer', 'created_at'], name='core_ride_custome_2f349b_idx'),
        ),
        migrations.RemoveField(
            model_name='ride',
            name='driver_name',
        ),
    ]
