# Generated by Django 6.1.1 on 2026-10-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_id', models.IntegerField()),
                ('event_type', models.CharField(default='ride_completed', max_length=50)),
                ('message', models.TextField(default='test message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('ride_id', 'event_type')},
            },
        ),
    ]
